### ISSUE TITLE
Crash when using 1.7.10 version of Hardcore Darkness...

### ISSUE THREAD

**Issue by Twilight13** [lumien231/Hardcore-Darkness#2]
The Minecraft client crashes when initializing the game when I have the Hardcore Darkness.jar file in my mods directory. I'm using Forge. Here is the crash data:

[00:31:46] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report
 ----
// This doesn't make any sense!

Time: 12/29/14 12:31 AM
Description: Initializing game

java.lang.VerifyError: (class: net/minecraft/client/renderer/EntityRenderer, method: func_78472_g signature: (F)V) Acces
sing value from uninitialized register 11
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:502)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
        at net.minecraft.client.main.Main.main(SourceFile:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:502)

-- Initialization --
Details:
Stacktrace:
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
        at net.minecraft.client.main.Main.main(SourceFile:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by GrimmLiberty** [comment]
I am getting a similar issue with Optifine in the 1.8.0 ... the log tells me there is a Float assigned to an Integer value, hence the error, but i am not so sure which mod is at fault. ALL other mods play well together and with Optifine, but that doesn't mean it isn't Optifine's fault.. heh

I posted the crash log on the curse mod download page a while ago...  (just found this)
