### ISSUE TITLE
CRASH when entering graphic settings

### ISSUE THREAD

**Issue by TomberWolf** [lumien231/Hardcore-Darkness#37]
We're running Hardcore Darkness on SMP at 1.12.2
When I want to enter the graphic settings, MC crashes.
S:GammaOverride=0.1

(What is the lowest possible value?)

```
Description: Unexpected error

java.lang.NoSuchFieldError: field_146501_h
	at lumien.hardcoredarkness.HardcoreDarkness.clientTick(HardcoreDarkness.java:145)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_947_HardcoreDarkness_clientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1910)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Elspar2** [comment]
I am getting the same crash.
https://paste.dimdev.org/monomogete.mccrash

**Comment by xhatz** [comment]
UP for @lumien231 boi, seems the crash is happening when OptiFine is installed... can anything be done about that please =3?

**Comment by xhatz** [comment]
UP again, still a thing, sadly... anyone having a solution :( ?

**Comment by Insane96** [comment]
Same crash ... found no solution

**Comment by Insane96** [comment]
I didn't try but setting GammaOverride to -1 could fix this

**Comment by sp614x** [comment]
It looks like Hardcore Darkness is trying to patch GuiVideoSettings (probably to disable some options).
The Video Settings in OptiFine are organized in a different way. There is no optionsRowList (field_146501_h) and this is probably why the patch fails.
