### ISSUE TITLE
1.8 Crash

### ISSUE THREAD

**Issue by craPatata** [lumien231/Hardcore-Darkness#4]
[17:56:36] [main/INFO]: Loading tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[17:56:36] [main/INFO]: Using primary tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[17:56:36] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:56:36] [main/INFO]: Calling tweak class com.mumfrey.liteloader.launch.LiteLoaderTweaker
[17:56:36] [main/INFO]: Bootstrapping LiteLoader 1.8
[17:56:37] [main/INFO]: Registering API provider class com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient
[17:56:37] [main/INFO]: Spawning API provider class 'com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient' ...
[17:56:37] [main/INFO]: API provider class 'com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient' provides API 'liteloader'
[17:56:37] [main/INFO]: Initialising API 'liteloader' ...
[17:56:37] [main/INFO]: LiteLoader begin PREINIT...
[17:56:37] [main/INFO]: Initialising Loader properties...
[17:56:37] [main/INFO]: Setting up logger...
[17:56:37] [main/INFO]: LiteLoader 1.8.0 starting up...
[17:56:37] [main/INFO]: Active Pack: 1.8-SNAPSHOT-r365-b46-2015-01-25_23-01-16
[17:56:37] [main/INFO]: Java reports OS="windows 8.1"
[17:56:37] [main/INFO]: Adding supported mod class prefix 'LiteMod'
[17:56:37] [main/INFO]: Enumerating class path...
[17:56:37] [main/INFO]: Class path separator=";"
[17:56:37] [main/INFO]: Class path entries=(
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\com\mumfrey\liteloader\1.8\liteloader-1.8.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.11\launchwrapper-1.11.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\net\minecraftforge\forge\1.8-11.14.0.1281-1.8\forge-1.8-11.14.0.1281-1.8.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.11\launchwrapper-1.11.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\com\typesafe\akka\akka-actor_2.11\2.3.3\akka-actor_2.11-2.3.3.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\com\typesafe\config\1.2.1\config-1.2.1.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-actors-migration_2.11\1.1.0\scala-actors-migration_2.11-1.1.0.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-compiler\2.11.1\scala-compiler-2.11.1.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\org\scala-lang\plugins\scala-continuations-library_2.11\1.0.2\scala-continuations-library_2.11-1.0.2.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\org\scala-lang\plugins\scala-continuations-plugin_2.11.1\1.0.2\scala-continuations-plugin_2.11.1-1.0.2.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-library\2.11.1\scala-library-2.11.1.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-parser-combinators_2.11\1.0.1\scala-parser-combinators_2.11-1.0.1.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-reflect\2.11.1\scala-reflect-2.11.1.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-swing_2.11\1.0.1\scala-swing_2.11-1.0.1.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\org\scala-lang\scala-xml_2.11\1.0.2\scala-xml_2.11-1.0.2.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\lzma\lzma\0.0.1\lzma-0.0.1.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\java3d\vecmath\1.5.2\vecmath-1.5.2.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.0.15.Final\netty-all-4.0.15.Final.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\17.0\guava-17.0.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.5.17\authlib-1.5.17.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\com\mojang\realms\1.6.1\realms-1.6.1.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.1\lwjgl-2.9.1.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.1\lwjgl_util-2.9.1.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\libraries\tv\twitch\twitch\6.5\twitch-6.5.jar
   classpathEntry=C:\Users\Mark\AppData\Roaming\.minecraft\versions\1.8\1.8.jar
)
[17:56:37] [main/INFO]: Registering discovery module EnumeratorModuleClassPath: [<Java Class Path>]
[17:56:37] [main/INFO]: Registering discovery module EnumeratorModuleFolder: [C:\Users\Mark\AppData\Roaming\.minecraft\mods]
[17:56:37] [main/INFO]: Registering discovery module EnumeratorModuleFolder: [C:\Users\Mark\AppData\Roaming\.minecraft\mods\1.8]
[17:56:37] [main/INFO]: Registering enumerator plugin DefaultEnumeratorPlugin: [com.mumfrey.liteloader.core.api.DefaultEnumeratorPlugin@5e316c74]
[17:56:37] [main/INFO]: Discovering tweaks on class path...
[17:56:37] [main/INFO]: Baking listener list for EnumerationObserver with 1 listeners
[17:56:37] [main/INFO]: Discovering valid mod files in folder C:\Users\Mark\AppData\Roaming\.minecraft\mods
[17:56:37] [main/INFO]: Inspecting jar metadata in 'HardcoreDarkness-1.2.jar'
[17:56:37] [main/INFO]: Ignoring C:\Users\Mark\AppData\Roaming\.minecraft\mods\HardcoreDarkness-1.2.jar
[17:56:37] [main/INFO]: Discovering valid mod files in folder C:\Users\Mark\AppData\Roaming\.minecraft\mods\1.8
[17:56:37] [main/INFO]: LiteLoader PREINIT complete
[17:56:37] [main/INFO]: Injecting required class transformer 'com.mumfrey.liteloader.transformers.event.EventProxyTransformer'
[17:56:37] [main/INFO]: Injecting required class transformer 'com.mumfrey.liteloader.launch.LiteLoaderTransformer'
[17:56:37] [main/INFO]: Injecting required class transformer 'com.mumfrey.liteloader.client.transformers.CrashReportTransformer'
[17:56:37] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.transformers.event.EventTransformer'
[17:56:37] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer'
[17:56:37] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer'
[17:56:37] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.client.transformers.MinecraftTransformer'
[17:56:37] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer'
[17:56:37] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[17:56:37] [main/INFO]: Forge Mod Loader version 8.0.14.1281 for Minecraft 1.8 loading
[17:56:37] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_31, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jre1.8.0_31
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoClassDefFoundError: cpw/mods/fml/relauncher/IFMLLoadingPlugin
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.URLClassLoader.defineClass(Unknown Source)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.URLClassLoader.access$100(Unknown Source)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.security.AccessController.doPrivileged(Native Method)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.forName0(Native Method)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.forName(Unknown Source)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:420)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:349)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:217)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:125)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.relauncher.IFMLLoadingPlugin
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 23 more
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NullPointerException
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 25 more
[17:56:37] [main/ERROR]: An error occurred trying to configure the minecraft home at C:\Users\Mark\AppData\Roaming\.minecraft for Forge Mod Loader
java.lang.NoClassDefFoundError: cpw/mods/fml/relauncher/IFMLLoadingPlugin
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_31]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_31]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_31]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_31]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_31]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_31]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_31]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_31]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_31]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_31]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:420) ~[forge-1.8-11.14.0.1281-1.8.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:349) ~[forge-1.8-11.14.0.1281-1.8.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:217) ~[forge-1.8-11.14.0.1281-1.8.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.8-11.14.0.1281-1.8.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.8-11.14.0.1281-1.8.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.8-11.14.0.1281-1.8.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:125) [forge-1.8-11.14.0.1281-1.8.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.relauncher.IFMLLoadingPlugin
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	... 23 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	... 23 more
Exception in thread "main" [17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoClassDefFoundError: cpw/mods/fml/relauncher/IFMLLoadingPlugin
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.URLClassLoader.defineClass(Unknown Source)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.URLClassLoader.access$100(Unknown Source)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.security.AccessController.doPrivileged(Native Method)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.forName0(Native Method)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.forName(Unknown Source)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:420)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:349)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:217)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:125)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.relauncher.IFMLLoadingPlugin
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 23 more
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NullPointerException
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[17:56:37] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 25 more

**Comment by lumien231** [comment]
Are you sure you are using the 1.8 and not the 1.7.10 version?

**Comment by craPatata** [comment]
I'm using the 1.8 version. It seems to have a conflict with Hopper Ducts mod.
